name: CratePublish

on:
  push:
    branches:
      - master
    paths:
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: cargo test --verbose
    - name: Login
      run: cargo login ${{ secrets.CRATES_IO }}
    - name: Publish
      run: cargo publish --verbose
